### ISSUE TITLE
Failed on first test with text files

### ISSUE THREAD

**Issue by MLD5000** [northloopforensics/DEPAD#2]
![image](https://user-images.githubusercontent.com/5643028/170913924-9a2c803d-f7f6-4410-a5c3-e44c419d1295.png)

Tested the app using 3 txt files, each with the same text content - the app closed and the error above appeared from the cmd line.

**Comment by northloopforensics** [comment]
This is a Windows issue with a ':' being in the file name.  The ':' has been replaced with a '-' in the timestamp.

Thanks!
