### ISSUE TITLE
Preview Byte Selection feature shows entire file

### ISSUE THREAD

**Issue by MLD5000** [northloopforensics/DEPAD#3]
I set the input/output folders and set the byte amount to remove from start of file.

Ran the byte selection feature and it shows the entire file instead of just the bytes to be removed or the file without the bytes - not sure what this feature does exactly.

![image](https://user-images.githubusercontent.com/5643028/170914413-c0fcedb7-5041-4925-abbb-8b15d8be48e8.png)

**Comment by northloopforensics** [comment]
I've updated this to show the hex view of the file data based on the number of bytes to be removed by the user.  Currently supports start-of-file preview only.  I will get end-of-file knocked out soon.
