### ISSUE TITLE
It takes like an hour to load files into the preview hex view

### ISSUE THREAD

**Issue by MLD5000** [northloopforensics/DEPAD#5]
Your test jpg file takes a while to load into the hex viewer - maybe write some logic that only loads data around the are that is being edtied?

**Comment by northloopforensics** [comment]
The user now has the option to keep a default setting that will only present 512 bytes of preview data from the target file. For example, the user selects to remove 8 bytes from the start of a file.  The preview will show bytes 9-520 in the window.

If the user wishes to still see all of the file data, they can uncheck the new check box and watch it all scroll by.
